import Homee from "@/components/icons/Homee";
export const LastRecord = [
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
  {
    header: "Last Records",
    color: "",
    icon: <Homee />,
    has: "-",
    num: " 1,000₮",
    p: "3 hours ago",
    h1: "Lending & Renting",
  },
];
